/// Generated by AssetsRefGenerator on 2020/05/18
class Res {
  static const String askAQuotation = "assets/askAQuotation.png";
  static const String background = "assets/background.png";
  static const String contract = "assets/contract.png";
  static const String enterprise = "assets/enterprise.png";
  static const String facebook = "assets/facebook.png";
  static const String file = "assets/file.png";
  static const String fullback = "assets/fullback.png";
  static const String google = "assets/google.png";
  static const String lawsuit = "assets/lawsuit.png";
  static const String legalopinion = "assets/legalopinion.png";
  static const String legaltip = "assets/legaltip.png";
  static const String logo = "assets/logo.png";
  static const String person = "assets/person.png";
  static const String StartALawsuit = "assets/StartALawsuit.png";
}
